steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '--file', 'Dockerfile_api', '-t', 'gcr.io/$PROJECT_ID/rimdian-api:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rimdian-api:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rimdian-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rimdian-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
  # Make sure traffic is routed to latest revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'rimdian-api'
      - '--to-latest'
images:
  - 'gcr.io/$PROJECT_ID/rimdian-api:$COMMIT_SHA'
