package common

var CurrenciesCodes = []string{"USD", "EUR", "GBP", "CAD", "AUD", "SGD", "JPY", "BGN", "CZK", "DKK", "HUF", "PLN", "RON", "SEK", "CHF", "ISK", "NOK", "HRK", "RUB", "TRY", "BRL", "CNY", "HKD", "IDR", "ILS", "INR", "KRW", "MXN", "MYR", "NZD", "PHP", "THB", "ZAR"}

var Currencies = []struct {
	Code   string
	Number string
	Digits int
	Name   string
	// Countries []string
}{
	// {
	// 	Code:   "AED",
	// 	Number: "784",
	// 	Digits: 2,
	// 	Name:   "United Arab Emirates dirham",
	// 	// Countries: ["united arab emirates"],
	// },
	// {
	// 	Code:   "AFN",
	// 	Number: "971",
	// 	Digits: 2,
	// 	Name:   "Afghan afghani",
	// 	// Countries: ["afghanistan"],
	// },
	// {
	// 	Code:   "ALL",
	// 	Number: "008",
	// 	Digits: 2,
	// 	Name:   "Albanian lek",
	// 	// Countries: ["albania"],
	// },
	// {
	// 	Code:   "AMD",
	// 	Number: "051",
	// 	Digits: 2,
	// 	Name:   "Armenian dram",
	// 	// Countries: ["armenia"],
	// },
	// {
	// 	Code:   "ANG",
	// 	Number: "532",
	// 	Digits: 2,
	// 	Name:   "Netherlands Antillean guilder",
	// 	// Countries: ["curaçao", "sint maarten"],
	// },
	// {
	// 	Code:   "AOA",
	// 	Number: "973",
	// 	Digits: 2,
	// 	Name:   "Angolan kwanza",
	// 	// Countries: ["angola"],
	// },
	// {
	// 	Code:   "ARS",
	// 	Number: "032",
	// 	Digits: 2,
	// 	Name:   "Argentine peso",
	// 	// Countries: ["argentina"],
	// },
	{
		Code:   "AUD",
		Number: "036",
		Digits: 2,
		Name:   "Australian dollar",
		// Countries: ["australia", "australian antarctic territory", "christmas island", "cocos (keeling) islands", "heard and mcdonald islands", "kiribati", "nauru", "norfolk island", "tuvalu"],
	},
	// {
	// 	Code:   "AWG",
	// 	Number: "533",
	// 	Digits: 2,
	// 	Name:   "Aruban florin",
	// 	// Countries: ["aruba"],
	// },
	// {
	// 	Code:   "AZN",
	// 	Number: "944",
	// 	Digits: 2,
	// 	Name:   "Azerbaijani manat",
	// 	// Countries: ["azerbaijan"],
	// },
	// {
	// 	Code:   "BAM",
	// 	Number: "977",
	// 	Digits: 2,
	// 	Name:   "Bosnia and Herzegovina convertible mark",
	// 	// Countries: ["bosnia and herzegovina"],
	// },
	// {
	// 	Code:   "BBD",
	// 	Number: "052",
	// 	Digits: 2,
	// 	Name:   "Barbados dollar",
	// 	// Countries: ["barbados"],
	// },
	// {
	// 	Code:   "BDT",
	// 	Number: "050",
	// 	Digits: 2,
	// 	Name:   "Bangladeshi taka",
	// 	// Countries: ["bangladesh"],
	// },
	{
		Code:   "BGN",
		Number: "975",
		Digits: 2,
		Name:   "Bulgarian lev",
		// Countries: ["bulgaria"],
	},
	// {
	// 	Code:   "BHD",
	// 	Number: "048",
	// 	Digits: 3,
	// 	Name:   "Bahraini dinar",
	// 	// Countries: ["bahrain"],
	// },
	// {
	// 	Code:   "BIF",
	// 	Number: "108",
	// 	Digits: 0,
	// 	Name:   "Burundian franc",
	// 	// Countries: ["burundi"],
	// },
	// {
	// 	Code:   "BMD",
	// 	Number: "060",
	// 	Digits: 2,
	// 	Name:   "Bermudian dollar",
	// 	// Countries: ["bermuda"],
	// },
	// {
	// 	Code:   "BND",
	// 	Number: "096",
	// 	Digits: 2,
	// 	Name:   "Brunei dollar",
	// 	// Countries: ["brunei", "singapore"],
	// },
	// {
	// 	Code:   "BOB",
	// 	Number: "068",
	// 	Digits: 2,
	// 	Name:   "Boliviano",
	// 	// Countries: ["bolivia"],
	// },
	// {
	// 	Code:   "BOV",
	// 	Number: "984",
	// 	Digits: 2,
	// 	Name:   "Bolivian Mvdol (funds code)",
	// 	// Countries: ["bolivia"],
	// },
	{
		Code:   "BRL",
		Number: "986",
		Digits: 2,
		Name:   "Brazilian real",
		// Countries: ["brazil"],
	},
	// {
	// 	Code:   "BSD",
	// 	Number: "044",
	// 	Digits: 2,
	// 	Name:   "Bahamian dollar",
	// 	// Countries: ["bahamas"],
	// },
	// {
	// 	Code:   "BTN",
	// 	Number: "064",
	// 	Digits: 2,
	// 	Name:   "Bhutanese ngultrum",
	// 	// Countries: ["bhutan"],
	// },
	// {
	// 	Code:   "BWP",
	// 	Number: "072",
	// 	Digits: 2,
	// 	Name:   "Botswana pula",
	// 	// Countries: ["botswana"],
	// },
	// {
	// 	Code:   "BYR",
	// 	Number: "974",
	// 	Digits: 0,
	// 	Name:   "Belarusian ruble",
	// 	// Countries: ["belarus"],
	// },
	// {
	// 	Code:   "BZD",
	// 	Number: "084",
	// 	Digits: 2,
	// 	Name:   "Belize dollar",
	// 	// Countries: ["belize"],
	// },
	{
		Code:   "CAD",
		Number: "124",
		Digits: 2,
		Name:   "Canadian dollar",
		// Countries: ["canada", "saint pierre and miquelon"],
	},
	// {
	// 	Code:   "CDF",
	// 	Number: "976",
	// 	Digits: 2,
	// 	Name:   "Congolese franc",
	// 	// Countries: ["democratic republic of congo"],
	// },
	// {
	// 	Code:   "CHE",
	// 	Number: "947",
	// 	Digits: 2,
	// 	Name:   "WIR Euro (complementary currency)",
	// 	// Countries: ["switzerland"],
	// },
	{
		Code:   "CHF",
		Number: "756",
		Digits: 2,
		Name:   "Swiss franc",
		// Countries: ["switzerland", "liechtenstein"],
	},
	// {
	// 	Code:   "CHW",
	// 	Number: "948",
	// 	Digits: 2,
	// 	Name:   "WIR Franc (complementary currency)",
	// 	// Countries: ["switzerland"],
	// },
	// {
	// 	Code:   "CLF",
	// 	Number: "990",
	// 	Digits: 0,
	// 	Name:   "Unidad de Fomento (funds code)",
	// 	// Countries: ["chile"],
	// },
	// {
	// 	Code:   "CLP",
	// 	Number: "152",
	// 	Digits: 0,
	// 	Name:   "Chilean peso",
	// 	// Countries: ["chile"],
	// },
	{
		Code:   "CNY",
		Number: "156",
		Digits: 2,
		Name:   "Chinese yuan",
		// Countries: ["china"],
	},
	// {
	// 	Code:   "COP",
	// 	Number: "170",
	// 	Digits: 2,
	// 	Name:   "Colombian peso",
	// 	// Countries: ["colombia"],
	// },
	// {
	// 	Code:   "COU",
	// 	Number: "970",
	// 	Digits: 2,
	// 	Name:   "Unidad de Valor Real",
	// 	// Countries: ["colombia"],
	// },
	// {
	// 	Code:   "CRC",
	// 	Number: "188",
	// 	Digits: 2,
	// 	Name:   "Costa Rican colon",
	// 	// Countries: ["costa rica"],
	// },
	// {
	// 	Code:   "CUC",
	// 	Number: "931",
	// 	Digits: 2,
	// 	Name:   "Cuban convertible peso",
	// 	// Countries: ["cuba"],
	// },
	// {
	// 	Code:   "CUP",
	// 	Number: "192",
	// 	Digits: 2,
	// 	Name:   "Cuban peso",
	// 	// Countries: ["cuba"],
	// },
	// {
	// 	Code:   "CVE",
	// 	Number: "132",
	// 	Digits: 0,
	// 	Name:   "Cape Verde escudo",
	// 	// Countries: ["cape verde"],
	// },
	{
		Code:   "CZK",
		Number: "203",
		Digits: 2,
		Name:   "Czech koruna",
		// Countries: ["czech republic"],
	},
	// {
	// 	Code:   "DJF",
	// 	Number: "262",
	// 	Digits: 0,
	// 	Name:   "Djiboutian franc",
	// 	// Countries: ["djibouti"],
	// },
	{
		Code:   "DKK",
		Number: "208",
		Digits: 2,
		Name:   "Danish krone",
		// Countries: ["denmark", "faroe islands", "greenland"],
	},
	// {
	// 	Code:   "DOP",
	// 	Number: "214",
	// 	Digits: 2,
	// 	Name:   "Dominican peso",
	// 	// Countries: ["dominican republic"],
	// },
	// {
	// 	Code:   "DZD",
	// 	Number: "012",
	// 	Digits: 2,
	// 	Name:   "Algerian dinar",
	// 	// Countries: ["algeria"],
	// },
	// {
	// 	Code:   "EGP",
	// 	Number: "818",
	// 	Digits: 2,
	// 	Name:   "Egyptian pound",
	// 	// Countries: ["egypt", "palestinian territories"],
	// },
	// {
	// 	Code:   "ERN",
	// 	Number: "232",
	// 	Digits: 2,
	// 	Name:   "Eritrean nakfa",
	// 	// Countries: ["eritrea"],
	// },
	// {
	// 	Code:   "ETB",
	// 	Number: "230",
	// 	Digits: 2,
	// 	Name:   "Ethiopian birr",
	// 	// Countries: ["ethiopia"],
	// },
	{
		Code:   "EUR",
		Number: "978",
		Digits: 2,
		Name:   "Euro",
		// Countries: ["andorra", "austria", "belgium", "cyprus", "estonia", "finland", "france", "germany", "greece", "ireland", "italy", "kosovo", "luxembourg", "malta", "monaco", "montenegro", "netherlands", "portugal", "san marino", "slovakia", "slovenia", "spain", "vatican city"],
	},
	// {
	// 	Code:   "FJD",
	// 	Number: "242",
	// 	Digits: 2,
	// 	Name:   "Fiji dollar",
	// 	// Countries: ["fiji"],
	// },
	// {
	// 	Code:   "FKP",
	// 	Number: "238",
	// 	Digits: 2,
	// 	Name:   "Falkland Islands pound",
	// 	// Countries: ["falkland islands"],
	// },
	{
		Code:   "GBP",
		Number: "826",
		Digits: 2,
		Name:   "Pound sterling",
		// Countries: ["united kingdom", "british crown dependencies (the  isle of man and the channel islands)", "south georgia and the south sandwich islands", "british antarctic territory", "british indian ocean territory"],
	},
	// {
	// 	Code:   "GEL",
	// 	Number: "981",
	// 	Digits: 2,
	// 	Name:   "Georgian lari",
	// 	// Countries: ["georgia"],
	// },
	// {
	// 	Code:   "GHS",
	// 	Number: "936",
	// 	Digits: 2,
	// 	Name:   "Ghanaian cedi",
	// 	// Countries: ["ghana"],
	// },
	// {
	// 	Code:   "GIP",
	// 	Number: "292",
	// 	Digits: 2,
	// 	Name:   "Gibraltar pound",
	// 	// Countries: ["gibraltar"],
	// },
	// {
	// 	Code:   "GMD",
	// 	Number: "270",
	// 	Digits: 2,
	// 	Name:   "Gambian dalasi",
	// 	// Countries: ["gambia"],
	// },
	// {
	// 	Code:   "GNF",
	// 	Number: "324",
	// 	Digits: 0,
	// 	Name:   "Guinean franc",
	// 	// Countries: ["guinea"],
	// },
	// {
	// 	Code:   "GTQ",
	// 	Number: "320",
	// 	Digits: 2,
	// 	Name:   "Guatemalan quetzal",
	// 	// Countries: ["guatemala"],
	// },
	// {
	// 	Code:   "GYD",
	// 	Number: "328",
	// 	Digits: 2,
	// 	Name:   "Guyanese dollar",
	// 	// Countries: ["guyana"],
	// },
	{
		Code:   "HKD",
		Number: "344",
		Digits: 2,
		Name:   "Hong Kong dollar",
		// Countries: ["hong kong", "macao"],
	},
	// {
	// 	Code:   "HNL",
	// 	Number: "340",
	// 	Digits: 2,
	// 	Name:   "Honduran lempira",
	// 	// Countries: ["honduras"],
	// },
	{
		Code:   "HRK",
		Number: "191",
		Digits: 2,
		Name:   "Croatian kuna",
		// Countries: ["croatia"],
	},
	// {
	// 	Code:   "HTG",
	// 	Number: "332",
	// 	Digits: 2,
	// 	Name:   "Haitian gourde",
	// 	// Countries: ["haiti"],
	// },
	{
		Code:   "HUF",
		Number: "348",
		Digits: 2,
		Name:   "Hungarian forint",
		// Countries: ["hungary"],
	},
	{
		Code:   "IDR",
		Number: "360",
		Digits: 0,
		Name:   "Indonesian rupiah",
		// Countries: ["indonesia"],
	},
	{
		Code:   "ILS",
		Number: "376",
		Digits: 2,
		Name:   "Israeli new shekel",
		// Countries: ["israel", "palestinian territories"],
	},
	{
		Code:   "INR",
		Number: "356",
		Digits: 2,
		Name:   "Indian rupee",
		// Countries: ["india"],
	},
	// {
	// 	Code:   "IQD",
	// 	Number: "368",
	// 	Digits: 3,
	// 	Name:   "Iraqi dinar",
	// 	// Countries: ["iraq"],
	// },
	// {
	// 	Code:   "IRR",
	// 	Number: "364",
	// 	Digits: 0,
	// 	Name:   "Iranian rial",
	// 	// Countries: ["iran"],
	// },
	{
		Code:   "ISK",
		Number: "352",
		Digits: 0,
		Name:   "Icelandic króna",
		// Countries: ["iceland"],
	},
	// {
	// 	Code:   "JMD",
	// 	Number: "388",
	// 	Digits: 2,
	// 	Name:   "Jamaican dollar",
	// 	// Countries: ["jamaica"],
	// },
	// {
	// 	Code:   "JOD",
	// 	Number: "400",
	// 	Digits: 3,
	// 	Name:   "Jordanian dinar",
	// 	// Countries: ["jordan"],
	// },
	{
		Code:   "JPY",
		Number: "392",
		Digits: 0,
		Name:   "Japanese yen",
		// Countries: ["japan"],
	},
	// {
	// 	Code:   "KES",
	// 	Number: "404",
	// 	Digits: 2,
	// 	Name:   "Kenyan shilling",
	// 	// Countries: ["kenya"],
	// },
	// {
	// 	Code:   "KGS",
	// 	Number: "417",
	// 	Digits: 2,
	// 	Name:   "Kyrgyzstani som",
	// 	// Countries: ["kyrgyzstan"],
	// },
	// {
	// 	Code:   "KHR",
	// 	Number: "116",
	// 	Digits: 2,
	// 	Name:   "Cambodian riel",
	// 	// Countries: ["cambodia"],
	// },
	// {
	// 	Code:   "KMF",
	// 	Number: "174",
	// 	Digits: 0,
	// 	Name:   "Comoro franc",
	// 	// Countries: ["comoros"],
	// },
	// {
	// 	Code:   "KPW",
	// 	Number: "408",
	// 	Digits: 0,
	// 	Name:   "North Korean won",
	// 	// Countries: ["north korea"],
	// },
	{
		Code:   "KRW",
		Number: "410",
		Digits: 0,
		Name:   "South Korean won",
		// Countries: ["south korea"],
	},
	// {
	// 	Code:   "KWD",
	// 	Number: "414",
	// 	Digits: 3,
	// 	Name:   "Kuwaiti dinar",
	// 	// Countries: ["kuwait"],
	// },
	// {
	// 	Code:   "KYD",
	// 	Number: "136",
	// 	Digits: 2,
	// 	Name:   "Cayman Islands dollar",
	// 	// Countries: ["cayman islands"],
	// },
	// {
	// 	Code:   "KZT",
	// 	Number: "398",
	// 	Digits: 2,
	// 	Name:   "Kazakhstani tenge",
	// 	// Countries: ["kazakhstan"],
	// },
	// {
	// 	Code:   "LAK",
	// 	Number: "418",
	// 	Digits: 0,
	// 	Name:   "Lao kip",
	// 	// Countries: ["laos"],
	// },
	// {
	// 	Code:   "LBP",
	// 	Number: "422",
	// 	Digits: 0,
	// 	Name:   "Lebanese pound",
	// 	// Countries: ["lebanon"],
	// },
	// {
	// 	Code:   "LKR",
	// 	Number: "144",
	// 	Digits: 2,
	// 	Name:   "Sri Lankan rupee",
	// 	// Countries: ["sri lanka"],
	// },
	// {
	// 	Code:   "LRD",
	// 	Number: "430",
	// 	Digits: 2,
	// 	Name:   "Liberian dollar",
	// 	// Countries: ["liberia"],
	// },
	// {
	// 	Code:   "LSL",
	// 	Number: "426",
	// 	Digits: 2,
	// 	Name:   "Lesotho loti",
	// 	// Countries: ["lesotho"],
	// },
	// {
	// 	Code:   "LTL",
	// 	Number: "440",
	// 	Digits: 2,
	// 	Name:   "Lithuanian litas",
	// 	// Countries: ["lithuania"],
	// },
	// {
	// 	Code:   "LVL",
	// 	Number: "428",
	// 	Digits: 2,
	// 	Name:   "Latvian lats",
	// 	// Countries: ["latvia"],
	// },
	// {
	// 	Code:   "LYD",
	// 	Number: "434",
	// 	Digits: 3,
	// 	Name:   "Libyan dinar",
	// 	// Countries: ["libya"],
	// },
	// {
	// 	Code:   "MAD",
	// 	Number: "504",
	// 	Digits: 2,
	// 	Name:   "Moroccan dirham",
	// 	// Countries: ["morocco"],
	// },
	// {
	// 	Code:   "MDL",
	// 	Number: "498",
	// 	Digits: 2,
	// 	Name:   "Moldovan leu",
	// 	// Countries: ["moldova (except  transnistria)"],
	// },
	// {
	// 	Code:   "MGA",
	// 	Number: "969",
	// 	Digits: 0,
	// 	Name:   "*[8] Malagasy ariary",
	// 	// Countries: ["madagascar"],
	// },
	// {
	// 	Code:   "MKD",
	// 	Number: "807",
	// 	Digits: 0,
	// 	Name:   "Macedonian denar",
	// 	// Countries: ["macedonia"],
	// },
	// {
	// 	Code:   "MMK",
	// 	Number: "104",
	// 	Digits: 0,
	// 	Name:   "Myanma kyat",
	// 	// Countries: ["myanmar"],
	// },
	// {
	// 	Code:   "MNT",
	// 	Number: "496",
	// 	Digits: 2,
	// 	Name:   "Mongolian tugrik",
	// 	// Countries: ["mongolia"],
	// },
	// {
	// 	Code:   "MOP",
	// 	Number: "446",
	// 	Digits: 2,
	// 	Name:   "Macanese pataca",
	// 	// Countries: ["macao"],
	// },
	// {
	// 	Code:   "MRO",
	// 	Number: "478",
	// 	Digits: 0,
	// 	Name:   "*[8] Mauritanian ouguiya",
	// 	// Countries: ["mauritania"],
	// },
	// {
	// 	Code:   "MUR",
	// 	Number: "480",
	// 	Digits: 2,
	// 	Name:   "Mauritian rupee",
	// 	// Countries: ["mauritius"],
	// },
	// {
	// 	Code:   "MVR",
	// 	Number: "462",
	// 	Digits: 2,
	// 	Name:   "Maldivian rufiyaa",
	// 	// Countries: ["maldives"],
	// },
	// {
	// 	Code:   "MWK",
	// 	Number: "454",
	// 	Digits: 2,
	// 	Name:   "Malawian kwacha",
	// 	// Countries: ["malawi"],
	// },
	{
		Code:   "MXN",
		Number: "484",
		Digits: 2,
		Name:   "Mexican peso",
		// Countries: ["mexico"],
	},
	// {
	// 	Code:   "MXV",
	// 	Number: "979",
	// 	Digits: 2,
	// 	Name:   "Mexican Unidad de Inversion (UDI) (funds code)",
	// 	// Countries: ["mexico"],
	// },
	{
		Code:   "MYR",
		Number: "458",
		Digits: 2,
		Name:   "Malaysian ringgit",
		// Countries: ["malaysia"],
	},
	// {
	// 	Code:   "MZN",
	// 	Number: "943",
	// 	Digits: 2,
	// 	Name:   "Mozambican metical",
	// 	// Countries: ["mozambique"],
	// },
	// {
	// 	Code:   "NAD",
	// 	Number: "516",
	// 	Digits: 2,
	// 	Name:   "Namibian dollar",
	// 	// Countries: ["namibia"],
	// },
	// {
	// 	Code:   "NGN",
	// 	Number: "566",
	// 	Digits: 2,
	// 	Name:   "Nigerian naira",
	// 	// Countries: ["nigeria"],
	// },
	// {
	// 	Code:   "NIO",
	// 	Number: "558",
	// 	Digits: 2,
	// 	Name:   "Nicaraguan córdoba",
	// 	// Countries: ["nicaragua"],
	// },
	{
		Code:   "NOK",
		Number: "578",
		Digits: 2,
		Name:   "Norwegian krone",
		// Countries: ["norway", "svalbard", "jan mayen", "bouvet island", "queen maud land", "peter i island"],
	},
	// {
	// 	Code:   "NPR",
	// 	Number: "524",
	// 	Digits: 2,
	// 	Name:   "Nepalese rupee",
	// 	// Countries: ["nepal"],
	// },
	{
		Code:   "NZD",
		Number: "554",
		Digits: 2,
		Name:   "New Zealand dollar",
		// Countries: ["cook islands", "new zealand", "niue", "pitcairn", "tokelau", "ross dependency"],
	},
	// {
	// 	Code:   "OMR",
	// 	Number: "512",
	// 	Digits: 3,
	// 	Name:   "Omani rial",
	// 	// Countries: ["oman"],
	// },
	// {
	// 	Code:   "PAB",
	// 	Number: "590",
	// 	Digits: 2,
	// 	Name:   "Panamanian balboa",
	// 	// Countries: ["panama"],
	// },
	// {
	// 	Code:   "PEN",
	// 	Number: "604",
	// 	Digits: 2,
	// 	Name:   "Peruvian nuevo sol",
	// 	// Countries: ["peru"],
	// },
	// {
	// 	Code:   "PGK",
	// 	Number: "598",
	// 	Digits: 2,
	// 	Name:   "Papua New Guinean kina",
	// 	// Countries: ["papua new guinea"],
	// },
	{
		Code:   "PHP",
		Number: "608",
		Digits: 2,
		Name:   "Philippine peso",
		// Countries: ["philippines"],
	},
	// {
	// 	Code:   "PKR",
	// 	Number: "586",
	// 	Digits: 2,
	// 	Name:   "Pakistani rupee",
	// 	// Countries: ["pakistan"],
	// },
	// {
	// 	Code:   "PLN",
	// 	Number: "985",
	// 	Digits: 2,
	// 	Name:   "Polish złoty",
	// 	// Countries: ["poland"],
	// },
	// {
	// 	Code:   "PYG",
	// 	Number: "600",
	// 	Digits: 0,
	// 	Name:   "Paraguayan guaraní",
	// 	// Countries: ["paraguay"],
	// },
	// {
	// 	Code:   "QAR",
	// 	Number: "634",
	// 	Digits: 2,
	// 	Name:   "Qatari riyal",
	// 	// Countries: ["qatar"],
	// },
	{
		Code:   "RON",
		Number: "946",
		Digits: 2,
		Name:   "Romanian new leu",
		// Countries: ["romania"],
	},
	// {
	// 	Code:   "RSD",
	// 	Number: "941",
	// 	Digits: 2,
	// 	Name:   "Serbian dinar",
	// 	// Countries: ["serbia"],
	// },
	{
		Code:   "RUB",
		Number: "643",
		Digits: 2,
		Name:   "Russian rouble",
		// Countries: ["russia", "abkhazia", "south ossetia"],
	},
	// {
	// 	Code:   "RWF",
	// 	Number: "646",
	// 	Digits: 0,
	// 	Name:   "Rwandan franc",
	// 	// Countries: ["rwanda"],
	// },
	// {
	// 	Code:   "SAR",
	// 	Number: "682",
	// 	Digits: 2,
	// 	Name:   "Saudi riyal",
	// 	// Countries: ["saudi arabia"],
	// },
	// {
	// 	Code:   "SBD",
	// 	Number: "090",
	// 	Digits: 2,
	// 	Name:   "Solomon Islands dollar",
	// 	// Countries: ["solomon islands"],
	// },
	// {
	// 	Code:   "SCR",
	// 	Number: "690",
	// 	Digits: 2,
	// 	Name:   "Seychelles rupee",
	// 	// Countries: ["seychelles"],
	// },
	// {
	// 	Code:   "SDG",
	// 	Number: "938",
	// 	Digits: 2,
	// 	Name:   "Sudanese pound",
	// 	// Countries: ["sudan"],
	// },
	{
		Code:   "SEK",
		Number: "752",
		Digits: 2,
		Name:   "Swedish krona/kronor",
		// Countries: ["sweden"],
	},
	{
		Code:   "SGD",
		Number: "702",
		Digits: 2,
		Name:   "Singapore dollar",
		// Countries: ["singapore", "brunei"],
	},
	// {
	// 	Code:   "SHP",
	// 	Number: "654",
	// 	Digits: 2,
	// 	Name:   "Saint Helena pound",
	// 	// Countries: ["saint helena"],
	// },
	// {
	// 	Code:   "SLL",
	// 	Number: "694",
	// 	Digits: 0,
	// 	Name:   "Sierra Leonean leone",
	// 	// Countries: ["sierra leone"],
	// },
	// {
	// 	Code:   "SOS",
	// 	Number: "706",
	// 	Digits: 2,
	// 	Name:   "Somali shilling",
	// 	// Countries: ["somalia"],
	// },
	// {
	// 	Code:   "SRD",
	// 	Number: "968",
	// 	Digits: 2,
	// 	Name:   "Surinamese dollar",
	// 	// Countries: ["suriname"],
	// },
	// {
	// 	Code:   "SSP",
	// 	Number: "728",
	// 	Digits: 2,
	// 	Name:   "South Sudanese pound",
	// 	// Countries: ["south sudan"],
	// },
	// {
	// 	Code:   "STD",
	// 	Number: "678",
	// 	Digits: 0,
	// 	Name:   "São Tomé and Príncipe dobra",
	// 	// Countries: ["são tomé and príncipe"],
	// },
	// {
	// 	Code:   "SYP",
	// 	Number: "760",
	// 	Digits: 2,
	// 	Name:   "Syrian pound",
	// 	// Countries: ["syria"],
	// },
	// {
	// 	Code:   "SZL",
	// 	Number: "748",
	// 	Digits: 2,
	// 	Name:   "Swazi lilangeni",
	// 	// Countries: ["swaziland"],
	// },
	{
		Code:   "THB",
		Number: "764",
		Digits: 2,
		Name:   "Thai baht",
		// Countries: ["thailand"],
	},
	// {
	// 	Code:   "TJS",
	// 	Number: "972",
	// 	Digits: 2,
	// 	Name:   "Tajikistani somoni",
	// 	// Countries: ["tajikistan"],
	// },
	// {
	// 	Code:   "TMT",
	// 	Number: "934",
	// 	Digits: 2,
	// 	Name:   "Turkmenistani manat",
	// 	// Countries: ["turkmenistan"],
	// },
	// {
	// 	Code:   "TND",
	// 	Number: "788",
	// 	Digits: 3,
	// 	Name:   "Tunisian dinar",
	// 	// Countries: ["tunisia"],
	// },
	// {
	// 	Code:   "TOP",
	// 	Number: "776",
	// 	Digits: 2,
	// 	Name:   "Tongan paʻanga",
	// 	// Countries: ["tonga"],
	// },
	{
		Code:   "TRY",
		Number: "949",
		Digits: 2,
		Name:   "Turkish lira",
		// Countries: ["turkey",  "northern cyprus"],
	},
	// {
	// 	Code:   "TTD",
	// 	Number: "780",
	// 	Digits: 2,
	// 	Name:   "Trinidad and Tobago dollar",
	// 	// Countries: ["trinidad and tobago"],
	// },
	// {
	// 	Code:   "TWD",
	// 	Number: "901",
	// 	Digits: 2,
	// 	Name:   "New Taiwan dollar",
	// 	// Countries: ["republic of china (taiwan)"],
	// },
	// {
	// 	Code:   "TZS",
	// 	Number: "834",
	// 	Digits: 2,
	// 	Name:   "Tanzanian shilling",
	// 	// Countries: ["tanzania"],
	// },
	// {
	// 	Code:   "UAH",
	// 	Number: "980",
	// 	Digits: 2,
	// 	Name:   "Ukrainian hryvnia",
	// 	// Countries: ["ukraine"],
	// },
	// {
	// 	Code:   "UGX",
	// 	Number: "800",
	// 	Digits: 2,
	// 	Name:   "Ugandan shilling",
	// 	// Countries: ["uganda"],
	// },
	{
		Code:   "USD",
		Number: "840",
		Digits: 2,
		Name:   "United States dollar",
		// Countries: ["american samoa", "barbados", "bermuda", "british indian ocean territory", "british virgin islands, caribbean netherlands", "ecuador", "el salvador", "guam", "haiti", "marshall islands", "federated states of micronesia", "northern mariana islands", "palau", "panama", "puerto rico", "timor-leste", "turks and caicos islands", "united states", "u.s. virgin islands", "zimbabwe"],
	},
	// {
	// 	Code:   "USN",
	// 	Number: "997",
	// 	Digits: 2,
	// 	Name:   "United States dollar (next day) (funds code)",
	// 	// Countries: ["united states"],
	// },
	// {
	// 	Code:   "USS",
	// 	Number: "998",
	// 	Digits: 2,
	// 	Name:   "United States dollar",
	// 	// Countries: ["united states"],
	// },
	// {
	// 	Code:   "UYI",
	// 	Number: "940",
	// 	Digits: 0,
	// 	Name:   "Uruguay Peso en Unidades Indexadas",
	// 	// Countries: ["uruguay"],
	// },
	// {
	// 	Code:   "UYU",
	// 	Number: "858",
	// 	Digits: 2,
	// 	Name:   "Uruguayan peso",
	// 	// Countries: ["uruguay"],
	// },
	// {
	// 	Code:   "UZS",
	// 	Number: "860",
	// 	Digits: 2,
	// 	Name:   "Uzbekistan som",
	// 	// Countries: ["uzbekistan"],
	// },
	// {
	// 	Code:   "VEF",
	// 	Number: "937",
	// 	Digits: 2,
	// 	Name:   "Venezuelan bolívar",
	// 	// Countries: ["venezuela"],
	// },
	// {
	// 	Code:   "VND",
	// 	Number: "704",
	// 	Digits: 0,
	// 	Name:   "Vietnamese dong",
	// 	// Countries: ["vietnam"],
	// },
	// {
	// 	Code:   "VUV",
	// 	Number: "548",
	// 	Digits: 0,
	// 	Name:   "Vanuatu vatu",
	// 	// Countries: ["vanuatu"],
	// },
	// {
	// 	Code:   "WST",
	// 	Number: "882",
	// 	Digits: 2,
	// 	Name:   "Samoan tala",
	// 	// Countries: ["samoa"],
	// },
	// {
	// 	Code:   "XAF",
	// 	Number: "950",
	// 	Digits: 0,
	// 	Name:   "CFA franc BEAC",
	// 	// Countries: ["cameroon", "central african republic", "republic of the congo", "chad", "equatorial guinea", "gabon"],
	// },
	// {
	// 	Code:   "XAG",
	// 	Number: "961",
	// 	Name:   "Silver (one troy ounce)",
	// },
	// {
	// 	Code:   "XAU",
	// 	Number: "959",
	// 	Name:   "Gold (one troy ounce)",
	// },
	// {
	// 	Code:   "XBA",
	// 	Number: "955",
	// 	Name:   "European Composite Unit (EURCO) (bond market unit) ",
	// },
	// {
	// 	Code:   "XBB",
	// 	Number: "956",
	// 	Name:   "European Monetary Unit (E.M.U.-6) (bond market unit) ",
	// },
	// {
	// 	Code:   "XBC",
	// 	Number: "957",
	// 	Name:   "European Unit of Account 9 (E.U.A.-9) (bond market unit) ",
	// },
	// {
	// 	Code:   "XBD",
	// 	Number: "958",
	// 	Name:   "European Unit of Account 17 (E.U.A.-17) (bond market unit) ",
	// },
	// {
	// 	Code: "XBT",
	// 	Name: "Bitcoin",
	// },
	// {
	// 	Code:   "XCD",
	// 	Number: "951",
	// 	Digits: 2,
	// 	Name:   "East Caribbean dollar",
	// 	// Countries: ["anguilla", "antigua and barbuda", "dominica", "grenada", "montserrat", "saint kitts and nevis", "saint lucia", "saint vincent and the grenadines"],
	// },
	// {
	// 	Code:   "XDR",
	// 	Number: "960",
	// 	Name:   "Special drawing rights",
	// 	// Countries: ["international monetary fund"],
	// },
	// {
	// 	Code: "XFU",
	// 	Name: "UIC franc (special settlement currency)",
	// 	// Countries: ["international union of railways"],
	// },
	// {
	// 	Code:   "XOF",
	// 	Number: "952",
	// 	Digits: 0,
	// 	Name:   "CFA franc BCEAO",
	// 	// Countries: ["benin", "burkina faso", "côte d\"ivoire", "guinea-bissau", "mali", "niger", "senegal", "togo"],
	// },
	// {
	// 	Code:   "XPD",
	// 	Number: "964",
	// 	Name:   "Palladium (one troy ounce)",
	// },
	// {
	// 	Code:   "XPF",
	// 	Number: "953",
	// 	Digits: 0,
	// 	Name:   "CFP franc (Franc du Pacifique)",
	// 	// Countries: ["french polynesia", "new caledonia", "wallis and futuna"],
	// },
	// {
	// 	Code:   "XPT",
	// 	Number: "962",
	// 	Name:   "Platinum (one troy ounce)",
	// },
	// {
	// 	Code:   "XTS",
	// 	Number: "963",
	// 	Name:   "Code reserved for testing purposes",
	// },
	// {
	// 	Code:   "XXX",
	// 	Number: "999",
	// 	Name:   "No currency",
	// },
	// {
	// 	Code:   "YER",
	// 	Number: "886",
	// 	Digits: 2,
	// 	Name:   "Yemeni rial",
	// 	// Countries: ["yemen"],
	// },
	{
		Code:   "ZAR",
		Number: "710",
		Digits: 2,
		Name:   "South African rand",
		// Countries: ["south africa"],
	},
	// {
	// 	Code:   "ZMW",
	// 	Number: "967",
	// 	Digits: 2,
	// 	Name:   "Zambian kwacha",
	// 	// Countries: ["zambia"],
	// },
}
