package common

var LanguageCodes = []string{
	"aa",
	"ab",
	"ae",
	"af",
	"ak",
	"am",
	"an",
	"ar",
	"as",
	"av",
	"ay",
	"az",
	"ba",
	"be",
	"bg",
	"bh",
	"bi",
	"bm",
	"bn",
	"bo",
	"br",
	"bs",
	"ca",
	"ce",
	"ch",
	"co",
	"cr",
	"cs",
	"cu",
	"cv",
	"cy",
	"da",
	"de",
	"dv",
	"dz",
	"ee",
	"el",
	"en",
	"eo",
	"es",
	"et",
	"eu",
	"fa",
	"ff",
	"fi",
	"fj",
	"fo",
	"fr",
	"fy",
	"ga",
	"gd",
	"gl",
	"gn",
	"gu",
	"gv",
	"ha",
	"he",
	"hi",
	"ho",
	"hr",
	"ht",
	"hu",
	"hy",
	"hz",
	"ia",
	"id",
	"ie",
	"ig",
	"ii",
	"ik",
	"io",
	"is",
	"it",
	"iu",
	"ja",
	"jv",
	"ka",
	"kg",
	"ki",
	"kj",
	"kk",
	"kl",
	"km",
	"kn",
	"ko",
	"kr",
	"ks",
	"ku",
	"kv",
	"kw",
	"ky",
	"la",
	"lb",
	"lg",
	"li",
	"ln",
	"lo",
	"lt",
	"lu",
	"lv",
	"mg",
	"mh",
	"mi",
	"mk",
	"ml",
	"mn",
	"mr",
	"ms",
	"mt",
	"my",
	"na",
	"nb",
	"nd",
	"ne",
	"ng",
	"nl",
	"nn",
	"no",
	"nr",
	"nv",
	"ny",
	"oc",
	"oj",
	"om",
	"or",
	"os",
	"pa",
	"pi",
	"pl",
	"ps",
	"pt",
	"qu",
	"rm",
	"rn",
	"ro",
	"ru",
	"rw",
	"sa",
	"sc",
	"sd",
	"se",
	"sg",
	"si",
	"sk",
	"sl",
	"sm",
	"sn",
	"so",
	"sq",
	"sr",
	"ss",
	"st",
	"su",
	"sv",
	"sw",
	"ta",
	"te",
	"tg",
	"th",
	"ti",
	"tk",
	"tl",
	"tn",
	"to",
	"tr",
	"ts",
	"tt",
	"tw",
	"ty",
	"ug",
	"uk",
	"ur",
	"uz",
	"ve",
	"vi",
	"vo",
	"wa",
	"wo",
	"xh",
	"yi",
	"yo",
	"za",
	"zh",
	"zu",
}

var Languages = []struct {
	Alpha2 string
	Name   string
}{
	{Alpha2: "aa", Name: "Afar"},
	{Alpha2: "ab", Name: "Abkhazian"},
	{Alpha2: "ae", Name: "Avestan"},
	{Alpha2: "af", Name: "Afrikaans"},
	{Alpha2: "ak", Name: "Akan"},
	{Alpha2: "am", Name: "Amharic"},
	{Alpha2: "an", Name: "Aragonese"},
	{Alpha2: "ar", Name: "Arabic"},
	{Alpha2: "as", Name: "Assamese"},
	{Alpha2: "av", Name: "Avaric"},
	{Alpha2: "ay", Name: "Aymara"},
	{Alpha2: "az", Name: "Azerbaijani"},
	{Alpha2: "ba", Name: "Bashkir"},
	{Alpha2: "be", Name: "Belarusian"},
	{Alpha2: "bg", Name: "Bulgarian"},
	{Alpha2: "bh", Name: "Bihari languages"},
	{Alpha2: "bi", Name: "Bislama"},
	{Alpha2: "bm", Name: "Bambara"},
	{Alpha2: "bn", Name: "Bengali"},
	{Alpha2: "bo", Name: "Tibetan"},
	{Alpha2: "br", Name: "Breton"},
	{Alpha2: "bs", Name: "Bosnian"},
	{Alpha2: "ca", Name: "Catalan; Valencian"},
	{Alpha2: "ce", Name: "Chechen"},
	{Alpha2: "ch", Name: "Chamorro"},
	{Alpha2: "co", Name: "Corsican"},
	{Alpha2: "cr", Name: "Cree"},
	{Alpha2: "cs", Name: "Czech"},
	{Alpha2: "cu", Name: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
	{Alpha2: "cv", Name: "Chuvash"},
	{Alpha2: "cy", Name: "Welsh"},
	{Alpha2: "da", Name: "Danish"},
	{Alpha2: "de", Name: "German"},
	{Alpha2: "dv", Name: "Divehi; Dhivehi; Maldivian"},
	{Alpha2: "dz", Name: "Dzongkha"},
	{Alpha2: "ee", Name: "Ewe"},
	{Alpha2: "el", Name: "Greek, Modern (1453-)"},
	{Alpha2: "en", Name: "English"},
	{Alpha2: "eo", Name: "Esperanto"},
	{Alpha2: "es", Name: "Spanish; Castilian"},
	{Alpha2: "et", Name: "Estonian"},
	{Alpha2: "eu", Name: "Basque"},
	{Alpha2: "fa", Name: "Persian"},
	{Alpha2: "ff", Name: "Fulah"},
	{Alpha2: "fi", Name: "Finnish"},
	{Alpha2: "fj", Name: "Fijian"},
	{Alpha2: "fo", Name: "Faroese"},
	{Alpha2: "fr", Name: "French"},
	{Alpha2: "fy", Name: "Western Frisian"},
	{Alpha2: "ga", Name: "Irish"},
	{Alpha2: "gd", Name: "Gaelic; Scottish Gaelic"},
	{Alpha2: "gl", Name: "Galician"},
	{Alpha2: "gn", Name: "Guarani"},
	{Alpha2: "gu", Name: "Gujarati"},
	{Alpha2: "gv", Name: "Manx"},
	{Alpha2: "ha", Name: "Hausa"},
	{Alpha2: "he", Name: "Hebrew"},
	{Alpha2: "hi", Name: "Hindi"},
	{Alpha2: "ho", Name: "Hiri Motu"},
	{Alpha2: "hr", Name: "Croatian"},
	{Alpha2: "ht", Name: "Haitian; Haitian Creole"},
	{Alpha2: "hu", Name: "Hungarian"},
	{Alpha2: "hy", Name: "Armenian"},
	{Alpha2: "hz", Name: "Herero"},
	{Alpha2: "ia", Name: "Interlingua (International Auxiliary Language Association)"},
	{Alpha2: "id", Name: "Indonesian"},
	{Alpha2: "ie", Name: "Interlingue; Occidental"},
	{Alpha2: "ig", Name: "Igbo"},
	{Alpha2: "ii", Name: "Sichuan Yi; Nuosu"},
	{Alpha2: "ik", Name: "Inupiaq"},
	{Alpha2: "io", Name: "Ido"},
	{Alpha2: "is", Name: "Icelandic"},
	{Alpha2: "it", Name: "Italian"},
	{Alpha2: "iu", Name: "Inuktitut"},
	{Alpha2: "ja", Name: "Japanese"},
	{Alpha2: "jv", Name: "Javanese"},
	{Alpha2: "ka", Name: "Georgian"},
	{Alpha2: "kg", Name: "Kongo"},
	{Alpha2: "ki", Name: "Kikuyu; Gikuyu"},
	{Alpha2: "kj", Name: "Kuanyama; Kwanyama"},
	{Alpha2: "kk", Name: "Kazakh"},
	{Alpha2: "kl", Name: "Kalaallisut; Greenlandic"},
	{Alpha2: "km", Name: "Central Khmer"},
	{Alpha2: "kn", Name: "Kannada"},
	{Alpha2: "ko", Name: "Korean"},
	{Alpha2: "kr", Name: "Kanuri"},
	{Alpha2: "ks", Name: "Kashmiri"},
	{Alpha2: "ku", Name: "Kurdish"},
	{Alpha2: "kv", Name: "Komi"},
	{Alpha2: "kw", Name: "Cornish"},
	{Alpha2: "ky", Name: "Kirghiz; Kyrgyz"},
	{Alpha2: "la", Name: "Latin"},
	{Alpha2: "lb", Name: "Luxembourgish; Letzeburgesch"},
	{Alpha2: "lg", Name: "Ganda"},
	{Alpha2: "li", Name: "Limburgan; Limburger; Limburgish"},
	{Alpha2: "ln", Name: "Lingala"},
	{Alpha2: "lo", Name: "Lao"},
	{Alpha2: "lt", Name: "Lithuanian"},
	{Alpha2: "lu", Name: "Luba-Katanga"},
	{Alpha2: "lv", Name: "Latvian"},
	{Alpha2: "mg", Name: "Malagasy"},
	{Alpha2: "mh", Name: "Marshallese"},
	{Alpha2: "mi", Name: "Maori"},
	{Alpha2: "mk", Name: "Macedonian"},
	{Alpha2: "ml", Name: "Malayalam"},
	{Alpha2: "mn", Name: "Mongolian"},
	{Alpha2: "mr", Name: "Marathi"},
	{Alpha2: "ms", Name: "Malay"},
	{Alpha2: "mt", Name: "Maltese"},
	{Alpha2: "my", Name: "Burmese"},
	{Alpha2: "na", Name: "Nauru"},
	{Alpha2: "nb", Name: "Bokmål, Norwegian; Norwegian Bokmål"},
	{Alpha2: "nd", Name: "Ndebele, North; North Ndebele"},
	{Alpha2: "ne", Name: "Nepali"},
	{Alpha2: "ng", Name: "Ndonga"},
	{Alpha2: "nl", Name: "Dutch; Flemish"},
	{Alpha2: "nn", Name: "Norwegian Nynorsk; Nynorsk, Norwegian"},
	{Alpha2: "no", Name: "Norwegian"},
	{Alpha2: "nr", Name: "Ndebele, South; South Ndebele"},
	{Alpha2: "nv", Name: "Navajo; Navaho"},
	{Alpha2: "ny", Name: "Chichewa; Chewa; Nyanja"},
	{Alpha2: "oc", Name: "Occitan (post 1500); Provençal"},
	{Alpha2: "oj", Name: "Ojibwa"},
	{Alpha2: "om", Name: "Oromo"},
	{Alpha2: "or", Name: "Oriya"},
	{Alpha2: "os", Name: "Ossetian; Ossetic"},
	{Alpha2: "pa", Name: "Panjabi; Punjabi"},
	{Alpha2: "pi", Name: "Pali"},
	{Alpha2: "pl", Name: "Polish"},
	{Alpha2: "ps", Name: "Pushto; Pashto"},
	{Alpha2: "pt", Name: "Portuguese"},
	{Alpha2: "qu", Name: "Quechua"},
	{Alpha2: "rm", Name: "Romansh"},
	{Alpha2: "rn", Name: "Rundi"},
	{Alpha2: "ro", Name: "Romanian; Moldavian; Moldovan"},
	{Alpha2: "ru", Name: "Russian"},
	{Alpha2: "rw", Name: "Kinyarwanda"},
	{Alpha2: "sa", Name: "Sanskrit"},
	{Alpha2: "sc", Name: "Sardinian"},
	{Alpha2: "sd", Name: "Sindhi"},
	{Alpha2: "se", Name: "Northern Sami"},
	{Alpha2: "sg", Name: "Sango"},
	{Alpha2: "si", Name: "Sinhala; Sinhalese"},
	{Alpha2: "sk", Name: "Slovak"},
	{Alpha2: "sl", Name: "Slovenian"},
	{Alpha2: "sm", Name: "Samoan"},
	{Alpha2: "sn", Name: "Shona"},
	{Alpha2: "so", Name: "Somali"},
	{Alpha2: "sq", Name: "Albanian"},
	{Alpha2: "sr", Name: "Serbian"},
	{Alpha2: "ss", Name: "Swati"},
	{Alpha2: "st", Name: "Sotho, Southern"},
	{Alpha2: "su", Name: "Sundanese"},
	{Alpha2: "sv", Name: "Swedish"},
	{Alpha2: "sw", Name: "Swahili"},
	{Alpha2: "ta", Name: "Tamil"},
	{Alpha2: "te", Name: "Telugu"},
	{Alpha2: "tg", Name: "Tajik"},
	{Alpha2: "th", Name: "Thai"},
	{Alpha2: "ti", Name: "Tigrinya"},
	{Alpha2: "tk", Name: "Turkmen"},
	{Alpha2: "tl", Name: "Tagalog"},
	{Alpha2: "tn", Name: "Tswana"},
	{Alpha2: "to", Name: "Tonga (Tonga Islands)"},
	{Alpha2: "tr", Name: "Turkish"},
	{Alpha2: "ts", Name: "Tsonga"},
	{Alpha2: "tt", Name: "Tatar"},
	{Alpha2: "tw", Name: "Twi"},
	{Alpha2: "ty", Name: "Tahitian"},
	{Alpha2: "ug", Name: "Uighur; Uyghur"},
	{Alpha2: "uk", Name: "Ukrainian"},
	{Alpha2: "ur", Name: "Urdu"},
	{Alpha2: "uz", Name: "Uzbek"},
	{Alpha2: "ve", Name: "Venda"},
	{Alpha2: "vi", Name: "Vietnamese"},
	{Alpha2: "vo", Name: "Volapük"},
	{Alpha2: "wa", Name: "Walloon"},
	{Alpha2: "wo", Name: "Wolof"},
	{Alpha2: "xh", Name: "Xhosa"},
	{Alpha2: "yi", Name: "Yiddish"},
	{Alpha2: "yo", Name: "Yoruba"},
	{Alpha2: "za", Name: "Zhuang; Chuang"},
	{Alpha2: "zh", Name: "Chinese"},
	{Alpha2: "zu", Name: "Zulu"},
}
